### PR TITLE
import sweettests

### LINKED ISSUE #4: Port stub data + equivalent sweettests from old repo

### PR DESCRIPTION
**Pull request by dauphin3**
turns out stub data was already in there... just brought over sweettests from old repo so we can merge and close this issue in lieu of building them out more in #5

### CODE REVIEW

**Comment by evomimic** [comment]
We can build out NEW tests in a later issue.

But the _definition of done_ for this issue includes sweetest actually running the tests we have defined so far successfully.

**Comment by evomimic** [comment]
I added sweetest script to `package.json`
and added holochain to cargo dependencies (in response to a cargo:warning I was getting):
``` 
warning: /Users/stevemelville/dev/map-proto/map-dev/map-descriptors2/crates/coordinator/descriptors/Cargo.toml: dependency (holochain) specified without providing a local path, Git repository, or version to use. This will be considered an error in future versions
```

Then tried `num run sweetest`. It failed to build, throwing a bunch of warnings and the following error:
```
warning: fatal error: too many errors emitted, stopping now [-ferror-limit=]
warning: 20 errors generated.

error: failed to run custom build command for `sysinfo v0.15.9`

Caused by:
  process didn't exit successfully: `/Users/stevemelville/dev/map-proto/map-dev/map-descriptors2/target/debug/build/sysinfo-a447466185af64dc/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("x86_64-apple-darwin")
  OPT_LEVEL = Some("z")
  HOST = Some("x86_64-apple-darwin")
  cargo:rerun-if-env-changed=CC_x86_64-apple-darwin
  CC_x86_64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_x86_64_apple_darwin
  CC_x86_64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = Some("clang")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-apple-darwin
  CFLAGS_x86_64-apple-darwin = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_apple_darwin
  CFLAGS_x86_64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
```

@dauphin3: I pushed my changes back to branch 4... so if you can try it out for yourself when you get a chance.

**Comment by dauphin3** [comment]
solution was to move dna into global space workdir, making sure to modify bundled path in happ.yaml accordingly, as well as file path in tests

**Review by evomimic — APPROVED** [review]
Approving this PR so we can get on with more robust testing. It compiles and runs successfully with sweetest, so the basic configuration setup seems to now work. But it doesn't actually execute any tests.

The results I observed were:
```
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running tests/descriptor_tests.rs (target/debug/deps/descriptor_tests-9be89ae2645d00fe)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/descriptors_integrity-d3f5a9cc4a8e6237)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/shared_types_descriptor-5ed2f097eb2af5c4)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s
```

**Pull request merged**
